import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { SideBar } from "./components/layout/sidebar/GroupSidebar";
import Header from "@/app/(public)/components/layout/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mdl-js`}
      >
        <SideBar />
        <main className="ml-64 min-h-screen bg-[#F4F9FF]">
          <div className="flex flex-col items-center flex-4">
            <Header />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
