import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "./components/layout/header/Header";
import { Toaster } from "sonner";
import Footer from "./components/layout/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="mdl-js">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mdl-js`}
      >
        <Toaster position="top-right" richColors/>
        <main className="flex flex-col w-full min-h-screen bg-[#F4F9FF]">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
